### ISSUE TITLE
Image Replacement

### ISSUE THREAD

**Issue by gabecorso** [BuddhistWalrus/gremlin#14]

**Comment by gabecorso** [comment]
Replace the Gremlin based Images on `<Splash />`, `<Gamestonk />`, and `<PG13 />` pages with the finished images available on the Google Drive

**Comment by gabecorso** [comment]
https://drive.google.com/drive/folders/1zW5Lg6MWIeh5LZ0lsoplF0LQ0j6DTyPo the images themselves

**Comment by schroeder-g** [comment]
A couple q's re: updating images:

- What is the desired image for the updated splash.js? Is it Gremlin.jpeg (the one with a gremlin holding "the accord")?
- the updated GameStonk.jpg in the Drive has Fiverr watermarks on it; should I still push with it in the repo?

Otherwise I've created a public bucket with the images uploaded.
